on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-Android:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }
      - name: 🏗️ Build Apk (arm64,android-x64)
        run: flutter build apk --split-per-abi --target-platform android-arm64,android-x64,android-arm --release

      - name: Upload armeabi-v7a apk artifact File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-armeabi-v7a-release.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload arm64-v8a apk artifact File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-arm64-v8a-release.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload x86_64 apk artifact File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-x86_64-release.apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }

      - run: |
          flutter pub get
          flutter build windows --release
      - name: Upload Windows build file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-windows-x86_64.zip
          path: build/windows/runner/Release

  build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev webkit2gtk-4.0
          flutter pub get
          flutter build linux --release
      - name: Upload linux build File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-linux-x86_64.zip
          path: build/linux/x64/release/bundle

  create-Release:
    needs:
      - build-Android
      - build-Windows
      - build-Linux

    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts File
        uses: actions/download-artifact@v3
        with:
          path: ~/artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            ~/artifacts/${{ env.BRANCH_NAME }}-${{ env.SHA }}-linux-x86_64.zip
            ~/artifacts/${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-armeabi-v7a-release.apk
            ~/artifacts/${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-arm64-v8a-release.apk
            ~/artifacts/${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-x86_64-release.apk
            ~/artifacts/${{ env.BRANCH_NAME }}-${{ env.SHA }}-windows-x86_64.zip
